// -------------------------------------------------------------------------
// Vendored, unedited, from the ragbaz design system:
//
//   design-system/generated/ragbaz_design.rs
//   source-digest: 6b90908977ac7024
//
// Regenerate there (`python3 generate.py`) and re-vendor; do not edit this file.
// -------------------------------------------------------------------------
// @generated by design-system/generate.py from tokens.toml + themes.toml
// source-digest: 6b90908977ac7024   (rust)
// DO NOT EDIT. Regenerate in the design system, then vendor the result.
// The token files are the source of truth; this is a projection of them.
//! ragbaz design tokens, generated. See design-system/tokens.toml.

use std::collections::HashMap;
use std::sync::OnceLock;

pub const SOURCE_DIGEST: &str = "6b90908977ac7024";
pub const DEFAULT_THEME: &str = "ragbaz";

pub const ROLES: &[(&str, &str)] = &[
    ("surface.page", "surface"),
    ("surface.inset", "surface"),
    ("surface.raise", "surface"),
    ("surface.chrome", "surface"),
    ("ink.emphasis", "ink"),
    ("ink.body", "ink"),
    ("ink.muted", "ink"),
    ("ink.faint", "ink"),
    ("ink.invert", "ink"),
    ("ink.link", "ink"),
    ("ink.code", "ink"),
    ("edge.rule", "edge"),
    ("edge.control", "edge"),
    ("edge.focus", "edge"),
    ("status.ok", "status"),
    ("status.warn", "status"),
    ("status.error", "status"),
    ("status.info", "status"),
    ("status.pending", "status"),
    ("delta.added", "delta"),
    ("delta.removed", "delta"),
    ("delta.moved", "delta"),
];

pub const SPACE_CELLS: [u8; 9] = [0, 0, 1, 1, 1, 2, 3, 4, 5];

pub const GLYPH_KEYS: &[&str] = &[
    "arrow_dn",
    "arrow_up",
    "bar_empty",
    "bar_full",
    "bar_half",
    "box_bl",
    "box_br",
    "box_h",
    "box_hv",
    "box_tl",
    "box_tr",
    "box_v",
    "box_vl",
    "box_vr",
    "branch",
    "bullet",
    "caret",
    "check",
    "corner",
    "cross",
    "dot",
    "dot_empty",
    "ellipsis",
    "lock",
    "marker_select",
    "rec",
    "rule",
    "tag",
    "warn",
];

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Set {
    Nerd,
    Unicode,
    Ascii,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ColorMode {
    TrueColor,
    Ansi256,
    Ansi16,
    None,
}

impl ColorMode {
    /// NO_COLOR off; FORCE_COLOR on and beats NO_COLOR; TERM=dumb off.
    pub fn detect() -> Self {
        // NO_COLOR is the standard and wins. RAGBAZ_NO_COLOR is honoured as
        // an explicit override so a box can pin it without touching the
        // environment every other tool reads.
        if std::env::var("NO_COLOR").is_ok() || std::env::var("RAGBAZ_NO_COLOR").is_ok() {
            return Self::None;
        }
        if std::env::var("FORCE_COLOR").is_ok() {
            return Self::from_env();
        }
        let term = std::env::var("TERM").unwrap_or_default();
        if term == "dumb" {
            return Self::None;
        }
        Self::from_env()
    }

    fn from_env() -> Self {
        let term = std::env::var("TERM").unwrap_or_default();
        let colorterm = std::env::var("COLORTERM").unwrap_or_default();
        if colorterm == "truecolor" || colorterm == "24bit" {
            Self::TrueColor
        } else if term.contains("256") {
            Self::Ansi256
        } else if term.is_empty() {
            Self::None
        } else {
            Self::Ansi16
        }
    }

    pub fn for_terminal(self) -> Self {
        Self::from_env()
    }
}

impl Set {
    /// nerd is opt-in, never detected; then narrow unicode -> ascii.
    ///
    /// A Rust process cannot ask stdio what encoding it is, so this reads the
    /// locale. If nothing advertises UTF-8, a unicode glyph would be mojibake,
    /// so ASCII is the honest fallback rather than an unreachable variant.
    pub fn detect() -> Self {
        if std::env::var("RAGBAZ_NERD_FONT").is_ok() {
            return Self::Nerd;
        }
        if locale_is_utf8() {
            Self::Unicode
        } else {
            Self::Ascii
        }
    }
}

/// True when the locale advertises UTF-8 in any of the usual variables.
pub fn locale_is_utf8() -> bool {
    ["LC_ALL", "LC_CTYPE", "LANG"].iter().any(|name| {
        std::env::var(name)
            .map(|v| v.to_ascii_uppercase().contains("UTF"))
            .unwrap_or(false)
    })
}

const ANSI16: [&str; 16] = [
    "#000000", "#cd0000", "#00cd00", "#cdcd00", "#0000ee", "#cd00cd", "#00cdcd", "#e5e5e5",
    "#7f7f7f", "#ff0000", "#00ff00", "#ffff00", "#5c5cff", "#ff00ff", "#00ffff", "#ffffff",
];
const CUBE: [u8; 6] = [0, 95, 135, 175, 215, 255];

fn rgb(colour: &str) -> (i32, i32, i32) {
    let h = colour.trim_start_matches('#');
    let p = |i: usize| i32::from_str_radix(&h[i..i + 2], 16).unwrap_or(0);
    (p(0), p(2), p(4))
}

fn dist(a: (i32, i32, i32), b: (i32, i32, i32)) -> i32 {
    let (r, g, bl) = (a.0 - b.0, a.1 - b.1, a.2 - b.2);
    2 * r * r + 4 * g * g + 3 * bl * bl
}

pub fn nearest256(colour: &str) -> u8 {
    let t = rgb(colour);
    let (mut best, mut bd) = (16u8, i32::MAX);
    for r in 0..6 {
        for g in 0..6 {
            for b in 0..6 {
                let d = dist(t, (CUBE[r] as i32, CUBE[g] as i32, CUBE[b] as i32));
                if d < bd {
                    bd = d;
                    let idx: u16 = 16 + 36 * r as u16 + 6 * g as u16 + b as u16;
                    best = idx as u8;
                }
            }
        }
    }
    for i in 0..24i32 {
        let v = 8 + 10 * i;
        if dist(t, (v, v, v)) < bd {
            bd = dist(t, (v, v, v));
            best = 232 + i as u8;
        }
    }
    for (i, h) in ANSI16.iter().enumerate() {
        let d = dist(t, rgb(h));
        if d < bd {
            bd = d;
            best = i as u8;
        }
    }
    best
}

pub fn nearest16(colour: &str) -> u8 {
    let t = rgb(colour);
    let mut best = 0u8;
    let mut bd = i32::MAX;
    for (i, h) in ANSI16.iter().enumerate() {
        let d = dist(t, rgb(h));
        if d < bd {
            bd = d;
            best = i as u8;
        }
    }
    best
}

/// theme -> role -> hex
pub fn themes() -> &'static HashMap<&'static str, HashMap<&'static str, &'static str>> {
    static MAP: OnceLock<HashMap<&'static str, HashMap<&'static str, &'static str>>> =
        OnceLock::new();
    MAP.get_or_init(|| {
        let mut out: HashMap<&'static str, HashMap<&'static str, &'static str>> = HashMap::new();
        let m = HashMap::new();
        out.insert("mono", m);
        let mut m = HashMap::new();
        m.insert("delta.added", "#3f6b2f");
        m.insert("delta.moved", "#7a4b12");
        m.insert("delta.removed", "#9b2c22");
        m.insert("edge.control", "#76776b");
        m.insert("edge.focus", "#91682c");
        m.insert("edge.rule", "#ded5c2");
        m.insert("ink.body", "#2b2822");
        m.insert("ink.code", "#234a63");
        m.insert("ink.emphasis", "#17150f");
        m.insert("ink.faint", "#a39a8b");
        m.insert("ink.invert", "#f6f2e9");
        m.insert("ink.link", "#7a4b12");
        m.insert("ink.muted", "#6d6659");
        m.insert("status.error", "#9b2c22");
        m.insert("status.info", "#234a63");
        m.insert("status.ok", "#3f6b2f");
        m.insert("status.pending", "#6d6659");
        m.insert("status.warn", "#8a6412");
        m.insert("surface.chrome", "#faf8f0");
        m.insert("surface.inset", "#f7f2e7");
        m.insert("surface.page", "#fffdf8");
        m.insert("surface.raise", "#ffffff");
        out.insert("ragbaz", m);
        let mut m = HashMap::new();
        m.insert("delta.added", "#8fbc6a");
        m.insert("delta.moved", "#d9a04a");
        m.insert("delta.removed", "#e0705f");
        m.insert("edge.control", "#55524a");
        m.insert("edge.focus", "#d9a04a");
        m.insert("edge.rule", "#3a362c");
        m.insert("ink.body", "#ddd7c8");
        m.insert("ink.code", "#8fb8d4");
        m.insert("ink.emphasis", "#f6f2e9");
        m.insert("ink.faint", "#6d6659");
        m.insert("ink.invert", "#17150f");
        m.insert("ink.link", "#d9a04a");
        m.insert("ink.muted", "#a39a8b");
        m.insert("status.error", "#e0705f");
        m.insert("status.info", "#8fb8d4");
        m.insert("status.ok", "#8fbc6a");
        m.insert("status.pending", "#a39a8b");
        m.insert("status.warn", "#d9b44a");
        m.insert("surface.chrome", "#1a1814");
        m.insert("surface.inset", "#1c1a15");
        m.insert("surface.page", "#14130f");
        m.insert("surface.raise", "#24211a");
        out.insert("ragbaz-night", m);
        let mut m = HashMap::new();
        m.insert("delta.added", "#2f5d22");
        m.insert("delta.moved", "#5a3608");
        m.insert("delta.removed", "#8c1f16");
        m.insert("edge.control", "#5a5a5a");
        m.insert("edge.focus", "#8a5a12");
        m.insert("edge.rule", "#d0d0d0");
        m.insert("ink.body", "#1a1a1a");
        m.insert("ink.code", "#1b3d55");
        m.insert("ink.emphasis", "#000000");
        m.insert("ink.faint", "#9a9a9a");
        m.insert("ink.invert", "#ffffff");
        m.insert("ink.link", "#5a3608");
        m.insert("ink.muted", "#5c5c5c");
        m.insert("status.error", "#8c1f16");
        m.insert("status.info", "#1b3d55");
        m.insert("status.ok", "#2f5d22");
        m.insert("status.pending", "#5c5c5c");
        m.insert("status.warn", "#7a5600");
        m.insert("surface.chrome", "#fafafa");
        m.insert("surface.inset", "#f4f4f2");
        m.insert("surface.page", "#ffffff");
        m.insert("surface.raise", "#ffffff");
        out.insert("ragbaz-white", m);
        out
    })
}

pub fn colorless_themes() -> &'static [&'static str] {
    &["mono"]
}

/// glyph key -> (nerd, unicode, ascii)
pub fn glyphs() -> &'static HashMap<&'static str, (&'static str, &'static str, &'static str)> {
    static MAP: OnceLock<HashMap<&'static str, (&'static str, &'static str, &'static str)>> =
        OnceLock::new();
    MAP.get_or_init(|| {
        let mut out = HashMap::new();
        out.insert("arrow_dn", ("", "↓", "v"));
        out.insert("arrow_up", ("", "↑", "^"));
        out.insert("bar_empty", ("░", "░", "."));
        out.insert("bar_full", ("█", "█", "#"));
        out.insert("bar_half", ("▌", "▌", "="));
        out.insert("box_bl", ("└", "└", "+"));
        out.insert("box_br", ("┘", "┘", "+"));
        out.insert("box_h", ("─", "─", "-"));
        out.insert("box_hv", ("┼", "┼", "+"));
        out.insert("box_tl", ("┌", "┌", "+"));
        out.insert("box_tr", ("┐", "┐", "+"));
        out.insert("box_v", ("│", "│", "|"));
        out.insert("box_vl", ("├", "├", "+"));
        out.insert("box_vr", ("┤", "┤", "+"));
        out.insert("branch", ("", "├─", "|-"));
        out.insert("bullet", ("•", "•", "*"));
        out.insert("caret", ("", "▏", "|"));
        out.insert("check", ("", "✓", "+"));
        out.insert("corner", ("", "└─", "`-"));
        out.insert("cross", ("", "✗", "x"));
        out.insert("dot", ("", "●", "*"));
        out.insert("dot_empty", ("", "○", "o"));
        out.insert("ellipsis", ("", "…", "..."));
        out.insert("lock", ("", "▣", "="));
        out.insert("marker_select", ("", "▸", "*"));
        out.insert("rec", ("", "●", "o"));
        out.insert("rule", ("", "─", "-"));
        out.insert("tag", ("", "#", "#"));
        out.insert("warn", ("", "⚠", "!"));
        out
    })
}

/// Resolve a glyph key through the active set.
pub fn glyph(key: &str, set: Set) -> &'static str {
    let (n, u, a) = match glyphs().get(key) {
        Some(v) => *v,
        None => return "?",
    };
    match set {
        Set::Nerd => n,
        Set::Unicode => u,
        Set::Ascii => a,
    }
}
